---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-hello
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-hello
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: chaos-monkey
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-list-hello
  apiGroup: rbac.authorization.k8s.io